### PR TITLE
Github action for running tests

### PR DESCRIPTION
**Pull request by siddharthab**
This should set up Github actions for running all Go tests recursively on all pull requests and pushes.

The configured Go version is Go 1.13.

### CODE REVIEW

**Comment by siddharthab** [comment]
The checks are currently failing as expected.

**Comment by siddharthab** [comment]
> We may also want to configure golangci-lint.

Yeah, there's an action for that -- https://github.com/actions-contrib/golangci-lint

**Comment by yipal** [comment]
looks good, thanks!

**Comment by josh-newman** [comment]
CC @jcharum

**Pull request merged**
